version: "3.8"

volumes:
    postgres_data:
    static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/apachelogservice/static
    depends_on:
        - db
    env_file:
        - .env
  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/apachelogservice/static
    ports:
        - 80:80
    depends_on:
        - web
