version: "3.8"

volumes:
    static_volume:

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/apachelogservice/static
    env_file:
        - .env
  nginx:
    image: nginx:1.19.5-alpine
    restart: always
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/apachelogservice/static
    ports:
        - 80:80
    depends_on:
        - web
