# Generated by Django 3.0.7 on 2021-04-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес запроса')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время запроса')),
                ('http_method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('HEAD', 'Head'), ('OPTIONS', 'Options'), ('CONNECT', 'Connect'), ('TRACE', 'Trace'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=7, verbose_name='HTTP Метод')),
                ('request_path', models.CharField(max_length=200, verbose_name='Адрес запроса')),
                ('http_protocol', models.CharField(max_length=10, verbose_name='HTTP протокол')),
                ('response_status_code', models.PositiveIntegerField(verbose_name='Статус ответа сервера')),
                ('content_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер объекта')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='URL исходной страницы')),
                ('user_agent', models.TextField(blank=True, max_length=500, null=True, verbose_name='Клиентское приложение')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
