# Generated by Django 3.0.7 on 2021-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='http_method',
            field=models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('HEAD', 'Head'), ('OPTIONS', 'Options'), ('CONNECT', 'Connect'), ('TRACE', 'Trace'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=7, verbose_name='HTTP Метод'),
        ),
    ]
