# Generated by Django 3.0.7 on 2021-04-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='http_protoc',
            new_name='http_protocol',
        ),
    ]
