# Generated by Django 3.0.7 on 2021-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210417_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
