# Generated by Django 3.0.7 on 2021-04-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20210417_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='content_legth',
            new_name='content_length',
        ),
    ]
