# Generated by Django 3.0.7 on 2021-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20210417_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='referer',
            field=models.URLField(blank=True, null=True, verbose_name='URL исходной страницы'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_agent',
            field=models.TextField(max_length=500, verbose_name='Клиентское приложение'),
        ),
    ]
