# Generated by Django 3.0.7 on 2021-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20210417_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_agent',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Клиентское приложение'),
        ),
    ]
